hosts: all
name: fetch join token file
gather_facts: false
tasks:
- name: fetch join token file
  ansible.builtin.fetch:
    src: /home/ubuntu/join_command.sh
    dest: ./join_command.sh
    flat: yes
